### ISSUE TITLE
howdoi

### ISSUE THREAD

**Issue by JohannesBuchner** [knadh/dns.toys#10]
Hi, this is awesome!

In particular, it should be useful for wifi hotspots where DNS works without login.

It would be cool to combine this with howdoi: https://pypi.org/project/howdoi/

By this I mean: query `dig howdoi.format.date.bash @dns.toys`, receive as response from the server (which replaced '.' with ' ', passed to howdoi) `date +%Y-%m-%d`

**Comment by knadh** [comment]
Hi @JohannesBuchner. howdoi looks quite cool. It looks like the responses can be arbitrarily long, multi-line, and formatted, which would make it unfit for DNS responses. If you're able to prototype and test this out, please do let me know.
