### ISSUE TITLE
Support number conversion between bases

### ISSUE THREAD

**Issue by varunlakkur** [knadh/dns.toys#11]
I often use calculator to convert from hex to decimal, decimal to binary and such. It would be useful to add support for this conversion in dns.toys. Something like this:

Example 1:
```
dig 11234dec-hex.base @dns.toys

1234HEX-DEC.		1	IN	TXT	"1234 HEX = 4660 DEC"
```

Example 2:
```
dig 1234dec-bin.base @dns.toys

1234DEC-BIN.		1	IN	TXT	"1234 DEC = 10011010010 BIN"
```

**Comment by varunlakkur** [comment]
I have some changes in a forked repo (https://github.com/knadh/dns.toys/compare/master...varunlakkur:master)

If you are okay taking the changes, I will submit a PR.

**Comment by knadh** [comment]
That's very cool @varunlakkur. Please do send a PR.

**Comment by knadh** [comment]
Merged in https://github.com/knadh/dns.toys/pull/13
