### ISSUE TITLE
About .NET Library and NuGet Package

### ISSUE THREAD

**Issue by fatihdgn** [knadh/dns.toys#14]
First of all, thanks for this service. It's great. 

I've developed a client library for interacting with dns.toys. It was also fun. It's in my profile, you can reach it from [here](https://github.com/fatihdgn/DnsToys.NET).
I've also published a package called DnsToys to NuGet, it's [here](https://www.nuget.org/packages/DnsToys/1.0.0).

Would you consider adding a section for the package?

**Comment by knadh** [comment]
Cool! I've linked the project in the README. Thanks.
