### ISSUE TITLE
Support for network speed

### ISSUE THREAD

**Issue by hjoshi123** [knadh/dns.toys#2]
Hi,

It would be helpful if we could also monitor upload/download speed using this.
Something like:

```
dig download.speed @dns.toys
dig upload.speed @dns.toys
```

Is it ok if I work on a PR for the same?

**Comment by knadh** [comment]
Interesting idea, but infeasible with UDP @hjoshi123. How would you go about doing this?

**Comment by r0psteev** [comment]
Hi here.
It seems to be technically feasible. The tool **iperf3** does perform speed test with udp.
I tried running it between two hosts, and observed the traffic as it peforms that.

It seems like, the iperf3 client sends multiple udp packets (like 906 of them), each of known size (1448 bytes),
and measures the total time it took to transfer them.

How the actual conversions to get the final bitrate in Mbps is performed from these metrics,
i don't actually know, and kind of afraid to read iperf source 😅.

![image](https://user-images.githubusercontent.com/53584323/173053258-09ee57fa-5540-4789-8f99-53354cd49c3b.png)

![image](https://user-images.githubusercontent.com/53584323/173052207-22dd4bda-4e02-4c72-8562-85b4800604c5.png)

However, this only reflects  udp transfer speed not the tcp transfer speed of the device, if that's what we want to measure.

**Comment by hjoshi123** [comment]
@knadh or we can have like a server to measure the speed.. our server measures the hit speed?
