### ISSUE TITLE
Help Pi Typo

### ISSUE THREAD

**Issue by coffeepotkiller** [knadh/dns.toys#21]
I noticed a small typo in the help output:

```
$ dig help @dns.toys | grep pi
help.                   1       IN      TXT     "return pi as TXT or A or AAAA record." "dig ip @dns.toys"
```

In the example command `ip` should be changed to `pi`

**Comment by jeffjose** [comment]
Fixed in  https://github.com/knadh/dns.toys/issues/17

**Comment by knadh** [comment]
Yep, this has already been fixed. Thanks!
