### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by mapl** [knadh/dns.toys#27]
Please add support for IPv6 to retrieve IPv6 addresses using "dig ip @dns.toys" or "dig ipv6 @dns.toys".

Unfortunately, the domain dns.toys is not IPv6 activated yet.

;; QUESTION SECTION:
;dns.toys.                      IN      AAAA

;; AUTHORITY SECTION:
dns.toys.               1800    IN      SOA     matt.ns.cloudflare.com. dns.cloudflare.com. 2279935843 10000 2400 604800 3600

**Comment by knadh** [comment]
I have enabled IPV6 on the server and have also recorded an AAAA record to dns.toys. Could you check if this works now?

**Comment by mapl** [comment]
Connection via IPv6 works now! But my IPv6 Address is not returned, but with an error.

```
;; QUESTION SECTION:
;ip.                            IN      A

;; ADDITIONAL SECTION:
.                       1       IN      TXT     "error: unable to detect IP."

;; Query time: 98 msec
;; SERVER: 2604:a880:400:d0::1352:6001#53(2604:a880:400:d0::1352:6001)
```

**Comment by knadh** [comment]
Thanks for the fix @mr-karan. @mapl it should work now.

**Comment by mapl** [comment]
@knadh Works now perfectly for both ipv6 and ipv4. thanks @mr-karan 

dig -6 ip @dns.toys
dig -4 ip @dns.toys
