### ISSUE TITLE
Support for epoch conversions

### ISSUE THREAD

**Issue by aneeraj** [knadh/dns.toys#39]
I had worked on adding support for epoch time conversions to human readable on my [fork](https://github.com/knadh/dns.toys/compare/master...aneeraj:dns.toys:master).  

```
% dig 784783800.epoch @127.0.0.1 -p 5354   

;; QUESTION SECTION:
;784783800.epoch.		IN	A

;; ANSWER SECTION:
784783800.		1	IN	TXT	"1994-11-14 09:00:00 +0530 IST"
```
If you are okay with this, I can send in the PR.

Thanks and have a happy weekend! :slightly_smiling_face:

**Comment by varunlakkur** [comment]
I like this idea. This is useful for me too. Can we have a switch for UTC or other timezones too? Something like:

```
❯ dig 784783800-UTC.epoch @127.0.0.1 -p 5354   

;; QUESTION SECTION:
;784783800.epoch.		IN	A

;; ANSWER SECTION:
784783800.		1	IN	TXT	"1994-11-14 09:00:00 UTC"
```

**Comment by aneeraj** [comment]
Hey @varunlakkur 

Thanks for the suggestion! I made a quick change such that the result now includes both UTC and local time.

```
% dig 784783800.epoch @127.0.0.1 -p 5354

;; QUESTION SECTION:
;784783800.epoch.		IN	A

;; ANSWER SECTION:
784783800.		1	IN	TXT	"1994-11-14 03:30:00 +0000 UTC" "1994-11-14 09:00:00 +0530 IST"
```

**Comment by knadh** [comment]
Thanks @aneeraj. Please do send a PR.
