### ISSUE TITLE
.fx converts based on old exchange rates

### ISSUE THREAD

**Issue by i-sanyam** [knadh/dns.toys#49]
<img width="695" alt="Screenshot 2022-11-11 at 11 37 15 PM" src="https://user-images.githubusercontent.com/26229336/201402215-282a6947-6637-4b58-94c2-4338f1be691b.png">

**Comment by knadh** [comment]
Sorry, missed this. You can change the `[fx].refresh_interval = "6h"` setting to refresh the rates more frequently.
