### ISSUE TITLE
Error to convert cidr to ip range

### ISSUE THREAD

**Issue by MadalinNitu** [knadh/dns.toys#5]
I got this error: 
`dig 10.100.0.0/24 @dns.toys
;; Warning: query response not set

; <<>> DiG 9.16.1-Ubuntu <<>> 10.100.0.0/24 @dns.toys
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 25240
;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;10.100.0.0/24.			IN	A

;; ADDITIONAL SECTION:
.			1	IN	TXT	"error: unknown query. try: dig help @dns.toys"

;; Query time: 116 msec
;; SERVER: 138.197.68.199#53(138.197.68.199)
;; WHEN: Thu Jun 09 11:01:16 EEST 2022
;; MSG SIZE  rcvd: 88
`

**Comment by knadh** [comment]
You missed the `.cidr` suffix. Should be:

`dig 10.100.0.0/24.cidr @dns.toys`
