### ISSUE TITLE
Guide to Run it Locally

### ISSUE THREAD

**Issue by Arthavruksha** [knadh/dns.toys#55]
I went through the README.md file to run DNS Toys locally but I am not able to somehow do it , 

Can you guys provide some video in which you set-up DNS Toys Locally ,

That would be really helpful !

Thanks

**Comment by knadh** [comment]
You have to have Go installed. Then, clone the repository locally and run `make build` which builds the binary.

Unfortunately, don't have the time to do a video. Maybe someone will.

**Comment by Arthavruksha** [comment]
Okay Sure

**Comment by vikhyat187** [comment]
I feel wordnet should also be installed @knadh?

**Comment by knadh** [comment]
Ah yes, if you want to enable the dictionary service.
