### ISSUE TITLE
Suggest usage of `drill -Q` instead of `dig +short`

### ISSUE THREAD

**Issue by lapo-luchini** [knadh/dns.toys#71]
Could be useful to add to documentation (and maybe to `help` command) the possibility to use `drill` instead of `dig` (and `drill -Q` instead of `dig +short`).

**Comment by knadh** [comment]
Hi @lapo-luchini. Haven't heard of `drill` before. Seems like it's not a widely used client. There are several other options, `dog`, `doggo` etc. It wouldn't be ideal to mention one of these arbitrarily. `dig` is almost universal.
