### ISSUE TITLE
Numbers support is limited

### ISSUE THREAD

**Issue by AbdullahDiaa** [knadh/dns.toys#8]
It seems that number to words support is limited only to bilions, after that the last digits with billion are used which results in wrong results:

e.g.
```sh
dig 9876543210000000.words @dns.toys
```

should be 

```sh
nine quadrillion ,
eight hundred seventy six trillion ,
five hundred forty three billion ,
two hundred ten million 
```

however the output is 

```sh
9876543210000000 = five hundred forty-three billion two hundred ten million"
```

**Comment by knadh** [comment]
Thanks for reporting this. Removed the lib and wrote a new algorithm for the conversion which now works up to the limit of int64 (~quintillion),
